### ISSUE TITLE
hide synonyms / stopwords in “root nodes” page

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#173]
We currently display synonyms and stopwords in "root nodes" page.

We shouldn't:

1. because change in synonyms and stopwords are rare, and must be done by advanced users (they have a lot of implications
2. we do not support editing them (and it's not a priority). If we support editing, in the future, they would have their own page.

So this issue is about not listing them in "root nodes" page.

**Comment by Jagrutiti** [comment]
Does this issue some backend work too? Or is just FE?

**Comment by diivi** [comment]
Alex mentioned this in out last meeting, it is backend only.

**Comment by Jagrutiti** [comment]
> Alex mentioned this in out last meeting, it is backend only.

It is assigned to you so I was confused.

**Comment by Jagrutiti** [comment]
Hey @alexgarel 

Here do I have to filter [get_all_root_nodes() ](https://github.com/openfoodfacts/taxonomy-editor/blob/main/backend/editor/entries.py#L350) function in `entries.py`?

I came to the conclusion because [the root node API](https://github.com/openfoodfacts/taxonomy-editor/blob/main/backend/editor/api.py#L180) calls that function.

Also for query, I should refer to [Neo4J ](https://neo4j.com/developer/cypher/filtering-show/)syntax?

**Comment by diivi** [comment]
@Jagrutiti I have opened a PR for this issue as I though it was unassigned - #187

**Comment by Jagrutiti** [comment]
> @Jagrutiti I have opened a PR for this issue as it was unassigned - #187

My bad.  Since you were working on the FE part I made the wrong assumption. I just saw your commits.
